### ISSUE TITLE
Untranc version

### ISSUE THREAD

**Issue by ioanalexme** [cstar-software/Untruncer#1]
Hello,
Great tool you have here. Can you tell me what version of Untranc did you compiled? (eventually the Git repo link).
Thanks a lot.

**Comment by genericptr** [comment]
Yeah, It's from Feb 6 02:06:50 2019 according to "git log"

> commit bd512b123bd681ea2daed1715501afba8e4ed252 (HEAD -> master, origin/master, origin/HEAD)
> Merge: b728bf9 24d1c2f
> Author: Federico Ponchio <ponchio@gmail.com>
> Date:   Wed Feb 6 02:06:50 2019 +0100
> 
>     Merge pull request #143 from ianwelsh/patch-1
>     
>     Add missing path argument
>
